.TH SPSTATUS 1 spstatus\-VERSION
.SH NAME
spstatus \- safal piya's status
.SH SYNOPSIS
.B spstatus
.RB [ \-v ]
.SH DESCRIPTION
spstatus is a custom status bar for dwm made personally for me.
.P
User are intended to expand the functionality as per their needs by editing the
source code.
.P
Right now, it just shows time with seconds and updates it every second.
